baseurl = "https://code-chf.github.io"
languageCode = "zh-Hans"
defaultContentLanguage = "zh"
title = "codechf的个人博客"
theme = "dream"

copyright = '<a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/"></a>本作品采用<a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/">知识共享署名-非商业性使用-相同方式共享 4.0 国际许可协议</a>进行许可。'

googleAnalytics = "UA-98295641-1"
  
enableRobotsTXT = true

hasCJKLanguage = true

## 是否开启disqus评论，不要和utteranc同时开启
# disqusShortname = "g1eny0ung"

## 配置 utteranc评论,教程参考 https://utteranc.es/
# [params.utteranc]
#   enable = true
#   repo = "code-chf/Eric0720-hugo-comment" ##换成自己得
#   issueTerm = "pathname"
#   theme = "github-light"
#   crossorigin="anonymous"


# Paginate = 4

[outputs]
  home = ["HTML", "RSS", "JSON"]

# https://gohugo.io/news/0.60.0-relnotes/
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
      
# 配置代码高亮
  [markup.highlight]
    lineNos = true
    style = "vs"



[params]
  background = "black"
  backgroundImage = "/me/background.jpg"
  linkColor = "seagreen"

  author = "CHENG-HF"
  description = "cheng-hf 的生活记录～"
  avatar = "/me/me/1.jpg"
  motto = "与其感慨路难行，不如马上出发。"
  categoriesLimitInHeader = 12
  headerBottomText = "记录生活，记录美好~"

  rss = true

## 配置 utteranc评论,教程参考 https://utteranc.es/
  #utterancesRepo = "code-chf/code-chf.github.io"

  valine = true
  LEANCLOUD_APP_ID = "IxV03G57m5LqJ7yGI28hfg44-gzGzoHsz"
  LEANCLOUD_APP_KEY = "NL8D7xjtE7NRz1uGhbMw8TC9"
  
  email = "chenghf122112@outlook.com"
  twitter = "@chenghfhf"
  facebook = "/hf.cheng.982"
  instagram = "huafeicheng"
  # mastodon = ""
  # linkedin = ""
  github = "code-chf"
  # stackoverflow = ""
  # codepen = ""
  qq = " "

  siteStartYear = 2019

  favicon = "/favicon.ico"

  highlightjs = true
  # highlightjsCDN = "https://cdn.jsdelivr.net/gh/highlightjs/cdn-release/build/highlight.min.js"
  highlightjsExtraLanguages = ["ocaml"]
  highlightjsTheme = "idea"
  highlightjsThemeDark = "atelier-seaside-dark"

  # search
  enableSearch = true

  # options
  showSummaryCoverInPost = true
  # hasTwitterEmbed = true

  # dark mode
  darkLinkColor = "darkseagreen"
  darkNav = true
  dark404 = true
  
